TRC-39 Initial Vue.JS styleguide
monosolutions/vuejs-style-guide pull request #1
Opened 2019-04-02 11:52 UTC by cosminlupu

Initial Vue.js style guide

2019-04-03 14:05 UTC, kremipn requested changes

2019-04-03 14:05 UTC, kremipn commented on README.md
> +# Mono Solutions JavaScript Style Guide() {
Maybe this shouldn't be called JavaScript?

2019-04-08 07:48 UTC, kremipn submitted a review, later dismissed

2019-04-08 08:04 UTC, IonutParaschiv requested changes

2019-04-08 08:04 UTC, IonutParaschiv commented on README.md
> +
Could be a good idea having an example on how to access store props from non vue classes?

2019-04-08 08:04 UTC, IonutParaschiv commented on README.md
> +* We primarily use mjest at Monosolutions.
is mjest a typo? 
```suggestion
* We primarily use jest at Monosolutions.
```

2019-04-08 08:07 UTC, IonutParaschiv approved these changes

2019-04-08 08:08 UTC, merged